# Generated by Django 4.0.4 on 2022-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('link_seemore', models.TextField()),
                ('image_new', models.ImageField(upload_to='')),
            ],
        ),
    ]
