# Generated by Django 3.1 on 2022-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='test_vui',
            field=models.TextField(blank=True),
        ),
    ]
