# Generated by Django 3.1 on 2022-05-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('id_foods', models.TextField()),
                ('bill_code', models.CharField(max_length=100, null=True)),
                ('active', models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('address_ship', models.TextField(null=True)),
                ('number_telephone', models.TextField(blank=True)),
                ('receiver', models.TextField(null=True)),
                ('coupon_code', models.CharField(default='100', max_length=20)),
                ('raw_price', models.TextField(max_length=100)),
                ('final_price', models.TextField(max_length=100, null=True)),
                ('statement_bill', models.IntegerField(choices=[(0, 'pending'), (1, 'delivering'), (2, 'delivered')], default=0)),
                ('paid_bill', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_food', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=200)),
                ('active', models.IntegerField(choices=[(0, 'no serve'), (1, 'serve')], default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
            ],
        ),
        migrations.DeleteModel(
            name='news',
        ),
    ]
