# Generated by Django 4.0.3 on 2022-06-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_cart_category_food_delete_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-date_created']},
        ),
    ]
