# Generated by Django 3.1 on 2022-05-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220508_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='category',
            new_name='category_food',
        ),
    ]
