# Generated by Django 3.1 on 2022-04-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220414_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('name_food', models.CharField(max_length=100)),
                ('bill_code', models.CharField(max_length=100, null=True)),
                ('active', models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0)),
            ],
        ),
    ]
