# Generated by Django 3.1 on 2022-04-18 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220418_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.TextField(default=datetime.datetime(2022, 4, 18, 20, 41, 22, 336168)),
        ),
    ]
