# Generated by Django 3.1 on 2022-04-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='name_food',
        ),
        migrations.AddField(
            model_name='cart',
            name='id_foods',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
