# Generated by Django 3.1 on 2022-04-18 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20220418_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_create',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.TextField(default=datetime.datetime(2022, 4, 18, 20, 43, 18, 805071)),
        ),
    ]
