# Generated by Django 3.1 on 2022-04-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20220417_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
