# Generated by Django 3.1 on 2022-04-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20220417_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='active',
            new_name='active_bill',
        ),
    ]
