# Generated by Django 3.1 on 2022-04-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20220417_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='active_bill',
            field=models.IntegerField(null=True),
        ),
    ]
