# Generated by Django 3.1 on 2022-04-18 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20220418_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 18, 19, 30, 29, 861100)),
        ),
    ]
