# Generated by Django 3.1 on 2022-04-18 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_auto_20220418_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
