# Generated by Django 3.1 on 2022-04-18 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_auto_20220418_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.TextField(default=datetime.datetime(2022, 4, 18, 19, 46, 53, 466647)),
        ),
    ]
