# Generated by Django 3.1 on 2022-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_remove_cart_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_add',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
