# Generated by Django 3.1 on 2022-04-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_cart_date_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_add',
        ),
        migrations.AddField(
            model_name='cart',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
