# Generated by Django 3.1 on 2022-04-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20220418_2043'),
        ('menu', '0022_auto_20220418_1951'),
    ]

    operations = [
    ]
