# Generated by Django 3.1 on 2022-04-19 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_auto_20220419_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.TextField(default=datetime.datetime(2022, 4, 19, 8, 28, 44, 158966)),
        ),
    ]
