# Generated by Django 3.1 on 2022-04-19 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_auto_20220419_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address_ship',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.TextField(default=datetime.datetime(2022, 4, 19, 8, 40, 50, 375398)),
        ),
    ]
