# Generated by Django 3.1 on 2022-04-19 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_auto_20220419_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address_ship',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.TextField(default=datetime.datetime(2022, 4, 19, 8, 44, 30, 297724)),
        ),
    ]
