# Generated by Django 3.1 on 2022-04-19 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0029_auto_20220419_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.TextField(default=datetime.datetime(2022, 4, 19, 8, 49, 26, 89101)),
        ),
    ]
