# Generated by Django 4.0.3 on 2022-04-23 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0030_auto_20220419_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.TextField(default=datetime.datetime(2022, 4, 23, 15, 46, 54, 576536)),
        ),
    ]
